name: Java Spark Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests with Maven
      run: mvn test --file pom.xml

